"""Key constants — mirrors src/constants/keys.ts."""
from __future__ import annotations

# GrowthBook feature flag keys
GROWTHBOOK_KEYS = {
    "ANALYTICS_DISABLED": "analytics_disabled",
    "FEEDBACK_SURVEY_DISABLED": "feedback_survey_disabled",
    "TIME_BASED_MC_CONFIG": "tengu_slate_heron",
    "DATADOG_SINK_KILLSWITCH": "datadog_sink_killswitch",
    "FIRST_PARTY_SINK_KILLSWITCH": "first_party_sink_killswitch",
    "EVENT_SAMPLING_CONFIG": "event_sampling_config",
    "SESSION_MEMORY_CONFIG": "session_memory_config",
    "POLICY_LIMITS_ENABLED": "policy_limits_enabled",
    "TEAM_MEMORY_SYNC_ENABLED": "team_memory_sync_enabled",
    "PROMPT_SUGGESTION_ENABLED": "prompt_suggestion_enabled",
    "REMOTE_MANAGED_SETTINGS_ENABLED": "remote_managed_settings_enabled",
    "SETTINGS_SYNC_ENABLED": "settings_sync_enabled",
    "AUTO_DREAM_ENABLED": "auto_dream_enabled",
    "MAGIC_DOCS_ENABLED": "magic_docs_enabled",
    "LSP_ENABLED": "lsp_enabled",
    "EXTRACT_MEMORIES_ENABLED": "extract_memories_enabled",
    "AGENT_SUMMARY_ENABLED": "agent_summary_enabled",
    "TOOL_USE_SUMMARY_ENABLED": "tool_use_summary_enabled",
    "TIPS_ENABLED": "tips_enabled",
    "VOICE_ENABLED": "voice_enabled",
    "PREVENT_SLEEP_ENABLED": "prevent_sleep_enabled",
    "NOTIFIER_ENABLED": "notifier_enabled",
    "AWAY_SUMMARY_ENABLED": "away_summary_enabled",
    "INTERNAL_LOGGING_ENABLED": "internal_logging_enabled",
    "DIAGNOSTIC_TRACKING_ENABLED": "diagnostic_tracking_enabled",
    "RATE_LIMIT_MOCKING_ENABLED": "rate_limit_mocking_enabled",
    "MOCK_RATE_LIMITS_ENABLED": "mock_rate_limits_enabled",
    "COMPACT_WARNING_ENABLED": "compact_warning_enabled",
    "POST_COMPACT_CLEANUP_ENABLED": "post_compact_cleanup_enabled",
    "MICRO_COMPACT_ENABLED": "micro_compact_enabled",
    "GROUPING_ENABLED": "grouping_enabled",
    "EMPTY_USAGE_ENABLED": "empty_usage_enabled",
    "FIRST_TOKEN_DATE_ENABLED": "first_token_date_enabled",
    "USAGE_FETCH_ENABLED": "usage_fetch_enabled",
    "vivian_AI_LIMITS_ENABLED": "vivian_ai_limits_enabled",
    "TOKEN_ESTIMATION_ENABLED": "token_estimation_enabled",
    "VCR_ENABLED": "vcr_enabled",
    "VOICE_STREAM_STT_ENABLED": "voice_stream_stt_enabled",
    "MCP_ENABLED": "mcp_enabled",
    "OAUTH_ENABLED": "oauth_enabled",
    "PLUGINS_ENABLED": "plugins_enabled",
}
