"""Tool name constants — mirrors src/constants/tools.ts."""
from __future__ import annotations

BASH_TOOL_NAME = "Bash"
FILE_READ_TOOL_NAME = "Read"
FILE_WRITE_TOOL_NAME = "Write"
FILE_EDIT_TOOL_NAME = "Edit"
GLOB_TOOL_NAME = "Glob"
GREP_TOOL_NAME = "Grep"
NOTEBOOK_EDIT_TOOL_NAME = "NotebookEdit"
TOOL_SEARCH_TOOL_NAME = "ToolSearch"
SLEEP_TOOL_NAME = "Sleep"
DISCOVER_SKILLS_TOOL_NAME = "DiscoverSkills"
TICK_TAG = "tick"

# Additional tool names from new subdirectory packages
AGENT_TOOL_NAME = "Agent"
ASK_USER_QUESTION_TOOL_NAME = "AskUserQuestion"
BRIEF_TOOL_NAME = "Brief"
CONFIG_TOOL_NAME = "Config"
ENTER_PLAN_MODE_TOOL_NAME = "EnterPlanMode"
EXIT_PLAN_MODE_TOOL_NAME = "ExitPlanMode"
ENTER_WORKTREE_TOOL_NAME = "EnterWorktree"
EXIT_WORKTREE_TOOL_NAME = "ExitWorktree"
FUZZY_FIND_TOOL_NAME = "FuzzyFind"
LSP_TOOL_NAME = "LSP"
MCP_TOOL_NAME = "Mcp"
MCP_AUTH_TOOL_NAME = "mcp__auth"
NOTEBOOK_EDIT_TOOL_NAME = "NotebookEdit"
POWERSHELL_TOOL_NAME = "PowerShell"
REPL_TOOL_NAME = "REPL"
REMOTE_TRIGGER_TOOL_NAME = "RemoteTrigger"
RENDER_DIFF_TOOL_NAME = "RenderDiff"
SCHEDULE_CRON_TOOL_NAME = "ScheduleCron"
SEND_MESSAGE_TOOL_NAME = "SendMessage"
SKILL_TOOL_NAME = "Skill"
SYNTHETIC_OUTPUT_TOOL_NAME = "SyntheticOutput"
TASK_CREATE_TOOL_NAME = "TaskCreate"
TASK_GET_TOOL_NAME = "TaskGet"
TASK_LIST_TOOL_NAME = "TaskList"
TASK_OUTPUT_TOOL_NAME = "TaskOutput"
TASK_STOP_TOOL_NAME = "TaskStop"
TASK_UPDATE_TOOL_NAME = "TaskUpdate"
TEAM_CREATE_TOOL_NAME = "TeamCreate"
TEAM_DELETE_TOOL_NAME = "TeamDelete"
TODO_WRITE_TOOL_NAME = "TodoWrite"
WEB_FETCH_TOOL_NAME = "WebFetch"
WEB_SEARCH_TOOL_NAME = "WebSearch"
