"""VIM module."""
from .engine import VimEngine, VimMode
from .motions import isInclusiveMotion, isLinewiseMotion, resolveMotion
from .operators import (
	executeIndent,
	executeJoin,
	executeLineOp,
	executeOpenLine,
	executeOperatorFind,
	executeOperatorG,
	executeOperatorGg,
	executeOperatorMotion,
	executeOperatorTextObj,
	executePaste,
	executeReplace,
	executeToggleCase,
	executeX,
)
from .textObjects import findTextObject
from .transitions import transition
from .types import (
	FIND_KEYS,
	MAX_VIM_COUNT,
	OPERATORS,
	SIMPLE_MOTIONS,
	TEXT_OBJ_SCOPES,
	TEXT_OBJ_TYPES,
	PersistentState,
	VimState,
	createInitialPersistentState,
	createInitialVimState,
	isOperatorKey,
	isTextObjScopeKey,
)

__all__ = [
	"FIND_KEYS",
	"MAX_VIM_COUNT",
	"OPERATORS",
	"PersistentState",
	"SIMPLE_MOTIONS",
	"TEXT_OBJ_SCOPES",
	"TEXT_OBJ_TYPES",
	"VimEngine",
	"VimMode",
	"VimState",
	"createInitialPersistentState",
	"createInitialVimState",
	"executeIndent",
	"executeJoin",
	"executeLineOp",
	"executeOpenLine",
	"executeOperatorFind",
	"executeOperatorG",
	"executeOperatorGg",
	"executeOperatorMotion",
	"executeOperatorTextObj",
	"executePaste",
	"executeReplace",
	"executeToggleCase",
	"executeX",
	"findTextObject",
	"isInclusiveMotion",
	"isLinewiseMotion",
	"isOperatorKey",
	"isTextObjScopeKey",
	"resolveMotion",
	"transition",
]
