"""Keybinding schema constants — mirrors src/keybindings/schema.ts."""

KEYBINDING_CONTEXTS = [
    "Global",
    "Chat",
    "Autocomplete",
    "Confirmation",
    "Help",
    "Transcript",
    "HistorySearch",
    "Task",
    "ThemePicker",
    "Settings",
    "Tabs",
    "Scroll",
    "Attachments",
    "Footer",
    "MessageSelector",
    "MessageActions",
    "DiffDialog",
    "ModelPicker",
    "Select",
    "Plugin",
]

KEYBINDING_CONTEXT_DESCRIPTIONS = {
    "Global": "Active everywhere, regardless of focus",
    "Chat": "When the chat input is focused",
    "Autocomplete": "When autocomplete menu is visible",
    "Confirmation": "When a confirmation/permission dialog is shown",
    "Help": "When the help overlay is open",
    "Transcript": "When viewing the transcript",
    "HistorySearch": "When searching command history (ctrl+r)",
    "Task": "When a task/agent is running in the foreground",
    "ThemePicker": "When the theme picker is open",
    "Settings": "When the settings menu is open",
    "Tabs": "When tab navigation is active",
    "Scroll": "When scroll and text selection handlers are active",
    "Attachments": "When navigating image attachments in a select dialog",
    "Footer": "When footer indicators are focused",
    "MessageSelector": "When the message selector (rewind) is open",
    "MessageActions": "When the message actions dialog is open",
    "DiffDialog": "When the diff dialog is open",
    "ModelPicker": "When the model picker is open",
    "Select": "When a select/list component is focused",
    "Plugin": "When the plugin dialog is open",
}

KEYBINDING_ACTIONS = [
    "app:interrupt",
    "app:exit",
    "app:toggleTodos",
    "app:toggleTranscript",
    "app:toggleBrief",
    "app:toggleTeammatePreview",
    "app:toggleTerminal",
    "app:redraw",
    "app:globalSearch",
    "app:quickOpen",
    "history:search",
    "history:previous",
    "history:next",
    "chat:cancel",
    "chat:killAgents",
    "chat:cycleMode",
    "chat:modelPicker",
    "chat:fastMode",
    "chat:thinkingToggle",
    "chat:submit",
    "chat:newline",
    "chat:undo",
    "chat:externalEditor",
    "chat:stash",
    "chat:imagePaste",
    "chat:messageActions",
    "autocomplete:accept",
    "autocomplete:dismiss",
    "autocomplete:previous",
    "autocomplete:next",
    "confirm:yes",
    "confirm:no",
    "confirm:previous",
    "confirm:next",
    "confirm:nextField",
    "confirm:previousField",
    "confirm:cycleMode",
    "confirm:toggle",
    "confirm:toggleExplanation",
    "tabs:next",
    "tabs:previous",
    "transcript:toggleShowAll",
    "transcript:exit",
    "historySearch:next",
    "historySearch:accept",
    "historySearch:cancel",
    "historySearch:execute",
    "task:background",
    "theme:toggleSyntaxHighlighting",
    "help:dismiss",
    "selection:copy",
    "attachments:next",
    "attachments:previous",
    "attachments:remove",
    "attachments:exit",
    "footer:up",
    "footer:down",
    "footer:next",
    "footer:previous",
    "footer:openSelected",
    "footer:clearSelection",
    "footer:close",
    "messageSelector:up",
    "messageSelector:down",
    "messageSelector:top",
    "messageSelector:bottom",
    "messageSelector:select",
    "messageActions:prev",
    "messageActions:next",
    "messageActions:top",
    "messageActions:bottom",
    "messageActions:prevUser",
    "messageActions:nextUser",
    "messageActions:escape",
    "messageActions:ctrlc",
    "messageActions:enter",
    "messageActions:c",
    "messageActions:p",
    "diff:dismiss",
    "diff:previousSource",
    "diff:nextSource",
    "diff:back",
    "diff:viewDetails",
    "diff:previousFile",
    "diff:nextFile",
    "modelPicker:decreaseEffort",
    "modelPicker:increaseEffort",
    "select:next",
    "select:previous",
    "select:accept",
    "select:cancel",
    "plugin:toggle",
    "plugin:install",
    "permission:toggleDebug",
    "settings:search",
    "settings:retry",
    "settings:close",
    "voice:pushToTalk",
]
