"""help command — mirrors src/commands/help/help.tsx.

Shows available commands, keybindings, and usage information.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...types.command import CommandContext, TextResult


def getHelpText(commands: list | None = None) -> str:
    """Build the full help text, optionally from a command registry."""
    lines = [
        "╔══════════════════════════════════════════════════╗",
        "║              Vivian AI — Help                    ║",
        "╚══════════════════════════════════════════════════╝",
        "",
        "Session & Navigation:",
        "  /help, /h           Show this help",
        "  /exit, /quit, /q    Exit Vivian CLI",
        "  /clear [caches|conversation]  Clear screen or state",
        "  /resume [id]        Resume a previous session",
        "  /session            Show current session info",
        "  /rename <name>      Rename current session",
        "  /rewind [n]         Rewind conversation N steps",
        "  /compact            Compact conversation context",
        "",
        "Configuration:",
        "  /config [key] [val] View or change settings",
        "  /model [name]       View or switch the active model",
        "  /theme [name]       Change color theme",
        "  /color <setting>    Adjust color settings",
        "  /output-style [v]   Set output verbosity (default|compact|verbose)",
        "  /permissions         Configure tool permissions",
        "  /privacy-settings    Manage privacy options",
        "  /hooks               Manage hook scripts",
        "  /keybindings         Show / customize keybindings",
        "  /vim                 Toggle VIM mode",
        "  /voice               Toggle voice input",
        "  /sandbox-toggle      Toggle sandbox mode",
        "",
        "Git & Version Control:",
        "  /init               Create vivian.md for this project",
        "  /commit             Generate a commit message",
        "  /commit-push-pr     Commit, push, and create a PR",
        "  /review [pr]        Review a pull request",
        "  /diff               Show and explain git diff",
        "  /branch [name]      Create or switch branches",
        "  /pr_comments         Review PR comments",
        "",
        "Code Analysis:",
        "  /doctor             Diagnose and fix project issues",
        "  /advisor [q]        Get architectural advice",
        "  /effort <task>      Estimate effort for a task",
        "  /brief              Toggle brief-only output mode",
        "  /init-verifiers     Create verification skills",
        "  /security-review    Security-focused code review",
        "",
        "Cost & Context:",
        "  /cost               Show session token cost",
        "  /usage              Show detailed usage stats",
        "  /extra-usage        Show extra usage details",
        "  /add-dir <path>     Add directory to workspace",
        "  /context            Show current context info",
        "  /files              List files in context",
        "  /copy               Copy last response to clipboard",
        "  /export [fmt]       Export conversation",
        "",
        "Tools & Plugins:",
        "  /mcp <action>       Manage MCP servers",
        "  /plugin <action>    Manage plugins",
        "  /skills             List available skills",
        "  /reload-plugins     Reload all plugins",
        "  /memory [q]         Query Vivian's memory",
        "  /agents             Manage sub-agents",
        "  /tasks              Show running tasks",
        "  /tools              List available tools",
        "",
        "─" * 52,
        "  Security & Pentesting Tools",
        "  (invoke via: use ssh connect <host>  /  ask Vivian to run a scan, etc.)",
        "─" * 52,
        "",
        "SSHTool — Persistent SSH sessions:",
        "  connect <host>              Connect (password or key auth)",
        "  exec <command>              Run command on connected host",
        "  disconnect                  Close SSH session",
        "  status                      Show connection info",
        "  upload <local> <remote>     Upload file via SCP",
        "  download <remote> <local>   Download file via SCP",
        "  port_forward <lport> <rhost> <rport>  SSH port forwarding",
        "  scan_ports <host> [range]   Port scan from remote host",
        "  check_sudo                  Check sudo privileges",
        "  find_suid                   Find SUID binaries (privesc)",
        "  enum_system                 Full system recon (OS/users/services/cron)",
        "",
        "TryHackMeTool — CTF / pentest workflow:",
        "  vpn_connect <config>        Connect to TryHackMe VPN",
        "  vpn_status                  Show VPN status",
        "  vpn_disconnect              Disconnect VPN",
        "  nmap_scan <ip>              Service/version discovery",
        "  gobuster <url> <wordlist>   Directory enumeration",
        "  nikto_scan <url>            Web server vulnerability scan",
        "  hydra_brute <svc> <target> <user> <wl>  Credential brute force",
        "  enum4linux <ip>             SMB/Windows enumeration",
        "  smb_client <ip> [share]     SMB share access",
        "  sqlmap <url>                SQL injection testing",
        "  john_crack <hash_file>      Hash cracking (John the Ripper)",
        "  linpeas_upload <ip>         Upload & run linpeas for privesc",
        "  submit_flag <flag>          Record a captured flag",
        "  flags_found                 List all flags captured this session",
        "  room_info <name>            Fetch TryHackMe room details",
        "  check_tools                 Check which CTF tools are installed",
        "",
        "AutoPentestTool — Fully autonomous pentesting framework:",
        "  auto_pwn <target>           Autonomous: scan→exploit→privesc→flags",
        "  quick_scan <target>         Fast top-1000 scan + CVE cross-reference",
        "  deep_scan <target>          All 65535 ports + full vuln DB scan",
        "  cve_scan <target>           Map open ports/services to CVE numbers",
        "  web_attack <url>            Auto-detect stack + exploit search",
        "  php_exploit <url>           40+ PHP-specific checks",
        "  java_exploit <url>          Java/Spring/Struts/WebLogic checks",
        "  smb_exploit <target>        EternalBlue / SMBGhost / SambaCry",
        "  ftp_exploit <target>        vsftpd backdoor / anonymous FTP",
        "  ssh_brute <target>          SSH brute force + hydra integration",
        "  vuln_lookup <svc> <ver>     Cross-reference 100+ CVE entries",
        "  exploit_search <cve|kw>     Search ExploitDB / Metasploit modules",
        "  kotb_defend                 KOTH defense hardening",
        "  kotb_attack <target>        KOTH attack + persistence",
        "  vulnhub_test <vm>           VulnHub VM testing guide",
        "  web_enum <url>              Full web enumeration",
        "  privesc_check <target>      Privilege escalation vector detection",
        "",
        "VulnScannerTool — Multi-language SAST (200+ patterns, 9 languages):",
        "  scan <path> [lang]          Auto-detect or specify language",
        "  scan_php / scan_java / scan_python / scan_js  Language-specific scans",
        "  scan_c / scan_go / scan_ruby / scan_dotnet    Language-specific scans",
        "  scan_sql <path>             SQL injection across all languages",
        "  scan_xss <path>             XSS across all languages",
        "  scan_injection <path>       All injection types (SQL/CMD/LDAP/SSTI)",
        "  scan_secrets <path>         Hardcoded passwords / API keys / tokens",
        "  scan_crypto <path>          Weak hashes / ciphers / insecure random",
        "  scan_config <path>          Debug mode / CORS / HSTS / cookie flags",
        "  audit_deps <path>           pip-audit + npm audit for known CVEs",
        "  report                      Consolidated report from last scan",
        "",
        "WebAuditTool — Live web app vulnerability scanner (OWASP Top 10):",
        "  full_scan <url>             Complete OWASP Top 10 audit",
        "  sqli_test <url>             15 SQLi payloads (error/boolean/time)",
        "  xss_test <url>              10 XSS payloads",
        "  csrf_check <url>            Detect forms missing CSRF tokens",
        "  ssrf_test <url>             AWS/GCP metadata / internal IP access",
        "  path_traversal <url>        11 LFI payloads + PHP wrappers",
        "  auth_check <url>            Login brute risk / session cookie flags",
        "  headers_check <url>         CSP / HSTS / X-Frame-Options check",
        "  cors_check <url>            Wildcard / origin reflection / creds",
        "  ssl_check <host>            TLS version / cert expiry / cipher check",
        "  info_disclosure <url>       .git / .env / phpinfo / admin panels",
        "  dir_enum <url>              50+ common paths + custom wordlist",
        "  form_fuzz <url>             Extract all forms/inputs for injection",
        "  cookie_audit <url>          HttpOnly / Secure / SameSite flags",
        "  api_scan <url>              API docs / unauthenticated endpoints",
        "",
        "CodeAuditTool — Deep code security audit with taint tracking:",
        "  audit <path>                Full audit (sinks/auth/crypto/input/DB/API)",
        "  taint_track <path> <src> <sink>  Track data flow to dangerous functions",
        "  auth_audit <path>           Hardcoded passwords / missing auth / JWT",
        "  crypto_audit <path>         10 crypto checks (MD5/SHA1/DES/ECB/RSA)",
        "  input_audit <path>          Unvalidated input to dangerous sinks",
        "  session_audit <path>        Session ID regen / cookie flags",
        "  file_audit <path>           Path traversal / world-writable / temp races",
        "  db_audit <path>             SQL concatenation / raw queries / hardcoded creds",
        "  api_audit <path>            Endpoint discovery / missing auth decorators",
        "  dependency_check <path>     Known vulnerable versions (lodash/jQuery/etc.)",
        "  compliance_check <path> owasp_asvs  OWASP ASVS V2–V8 mapping",
        "  fix_report                  Prioritized 4-phase remediation plan",
        "  diff_audit <old> <new>      Audit new/modified code between versions",
        "",
        "THMWriteupTool — Write-up DB + auto-exploit engine:",
        "  search <room_name>          Search GitHub + web for write-ups",
        "  ingest <url>                Fetch and parse a write-up URL",
        "  ingest_github <name>        Auto-search GitHub and ingest top write-ups",
        "  fingerprint <ip>            Identify which THM room a target belongs to",
        "  auto_exploit <ip>           Auto-exploit using write-up knowledge",
        "  kotb_speedrun <ip>          KOTH speed-run with pre-loaded exploits",
        "  db_list / db_search / db_show  Browse the write-up database",
        "  db_stats / db_export / db_import  Manage the database",
        "  build_index                 Rebuild room fingerprint index",
        "",
        "ParsecVisionTool — Screen capture overlay + AI object detection:",
        "  start [window_title]        Start OpenGL overlay on a window",
        "  stop / status               Stop overlay / check status",
        "  capture [path]              Capture annotated screenshot",
        "  db_add <name> <path>        Add image to recognition database",
        "  db_remove / db_list         Manage image database",
        "  db_match <path>             Match image against database",
        "  db_match_screen             Match current screen against DB",
        "  detect_objects [thresh]     Detect moving objects on screen",
        "  label_objects               Label detected objects with AI",
        "  motion_regions              Show motion detection regions",
        "  configure <key> <val>       Change sensitivity/FPS/colors",
        "  check_deps                  Check OpenCV/OpenGL dependencies",
        "",
        "DMAMemoryTool — PCILeech FPGA DMA memory scanner (75T/35T):",
        "  connect [fpga|usb3380]      Connect to DMA card",
        "  list_processes              List all running processes",
        "  attach <name|pid>           Attach to a process",
        "  scan <value> <type>         Exact-match first scan",
        "  scan_range <min> <max> <type>  Range scan",
        "  scan_unknown <type>         Store all addresses (unknown scan)",
        "  next_scan <value>           Narrow by exact value",
        "  next_changed/unchanged/increased/decreased  Relative narrow",
        "  results [limit]             Show current scan results",
        "  freeze <addr> <type> <val>  Lock value in memory",
        "  thaw <addr> / thaw_all      Stop freezing address(es)",
        "  search_string <text>        Search string in memory",
        "  search_aob <pattern>        AoB scan: '48 8B ? ? 00'",
        "  pointers_to <addr>          Find pointers to address",
        "  resolve_chain <base> <offs> Follow pointer chain",
        "  read/write <addr> <type>    Direct memory access",
        "  check_deps                  Check vmmpy/numpy installed",
        "─" * 52,
        "",
        "UI & Status:",
        "  /status             Show system status",
        "  /stats              Show session statistics",
        "  /plan [task]        Enter plan mode",
        "  /fast               Toggle fast mode",
        "  /feedback [msg]     Send feedback",
        "  /ide                Open in IDE",
        "  /desktop            Desktop app controls",
        "  /terminal-setup     Configure terminal",
        "  /tag <name>         Tag current session",
        "  /summary            Generate session summary",
        "  /share              Share conversation",
        "  /stickers           Sticker picker",
        "",
        "Keybindings:",
        "  Ctrl+C              Interrupt current operation",
        "  Ctrl+D              Exit (on empty line)",
        "  Ctrl+R              Search command history",
        "  Ctrl+L              Clear screen",
        "  Up/Down             Navigate history",
        "  Tab                 Autocomplete",
        "  Escape              Cancel / exit mode",
        "",
        "Type any message to chat with Vivian AI.",
    ]

    if commands:
        lines.insert(4, "Available commands:")
        for c in sorted(commands, key=lambda x: x.name):
            if getattr(c, "is_enabled", True):
                lines.insert(5, f"  /{c.name:<20} {c.description}")

    return "\n".join(lines)


async def call(args: str, context: CommandContext) -> TextResult:
    """Show help."""
    from ...types.command import TextResult

    registry = getattr(context, "registry", None)
    command_registry = getattr(context, "command_registry", None)

    if registry and hasattr(registry, "get_enabled_commands"):
        cmds = registry.get_enabled_commands()
    elif command_registry and hasattr(command_registry, "get_enabled_commands"):
        cmds = command_registry.get_enabled_commands()
    else:
        cmds = None

    return TextResult(getHelpText(cmds))


get_help_text = getHelpText
getHelpText_ = getHelpText
