"""codegen.py — C++ and Python SDK generation for UESDKGen.

Public API:
  generate_sdk(names, objects, cfg) -> str
    cfg keys:
      sdk_lang    'cpp' | 'python'
      sdk_target  'native' | 'dma' | 'both'
      gobj_va     hex string
      gnam_va     hex string
      name_off    hex string
      namestr_off hex string
      is64        bool
      source_desc str
"""
from __future__ import annotations

import io
from typing import Dict, List


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _collect_classes(objects: List[Dict], limit: int = 300) -> List[str]:
    """Return sorted list of UE3-style type names from the object dump."""
    return sorted({
        o["name"] for o in objects
        if o["name"]
        and len(o["name"]) > 1
        and o["name"][0] in ("U", "A", "F", "E")
        and o["name"].isidentifier()
    })[:limit]


# ─────────────────────────────────────────────────────────────────────────────
# C++ generation
# ─────────────────────────────────────────────────────────────────────────────

def _gen_cpp(names: Dict[int, str], objects: List[Dict], cfg: dict) -> str:
    gobj_va  = cfg["gobj_va"]
    gnam_va  = cfg["gnam_va"]
    noff     = cfg["name_off"]
    nstroff  = cfg["namestr_off"]
    is64     = cfg["is64"]
    target   = cfg["sdk_target"]
    src_desc = cfg.get("source_desc", "offline")

    ptr_type = "DWORD64" if is64 else "DWORD"
    ptr_sz   = 8 if is64 else 4
    class_names = _collect_classes(objects)

    buf = io.StringIO()
    w   = buf.write

    w("// ==================================================================\n")
    w("// Unreal Engine 3 — Auto-generated C++ SDK skeleton\n")
    w(f"// Generated by UESDKGen  |  source: {src_desc}\n")
    w(f"// GObjects: {gobj_va}  GNames: {gnam_va}\n")
    w(f"// Names: {len(names):,}   Objects: {len(objects):,}\n")
    w("// ==================================================================\n\n")
    w("#pragma once\n#include <windows.h>\n#include <vector>\n#include <string>\n\n")

    w("// ── Engine offsets ─────────────────────────────────────────────\n")
    w(f"constexpr {ptr_type} GOBJECTS_VA   = {gobj_va};\n")
    w(f"constexpr {ptr_type} GNAMES_VA     = {gnam_va};\n")
    w(f"constexpr DWORD      NAME_FIELD_OFF = {noff};\n")
    w(f"constexpr DWORD      NAME_STR_OFF   = {nstroff};\n\n")

    w("template <class T>\nstruct TArray {\n")
    w(f"    T*    Data;   // +0x00\n")
    w(f"    DWORD Count;  // +0x{ptr_sz:02X}\n")
    w(f"    DWORD Max;    // +0x{ptr_sz + 4:02X}\n")
    w("};\n\n")

    w("struct FNameEntry {\n")
    w(f"    BYTE  Pad[{nstroff}];\n")
    w( "    char  Name[512];  // ASCII\n};\n\n")

    w("struct FName {\n")
    w("    DWORD Index;\n    DWORD Number;\n};\n\n")

    w("struct UObject {\n")
    w(f"    BYTE  Pad[{noff}];\n")
    w( "    FName Name;\n};\n\n")

    if class_names:
        w("// ── Forward declarations ───────────────────────────────────────\n")
        for cn in class_names:
            w(f"struct {cn};\n")
        w("\n")

    # ── Native section ──────────────────────────────────────────────────────
    if target in ("native", "both"):
        w("// ==================================================================\n")
        w("// NATIVE SDK  —  direct pointer access (local DLL / trainer)\n")
        w("// ==================================================================\n\n")

        w(f"inline TArray<UObject*>*    GObjObjects =\n"
          f"    reinterpret_cast<TArray<UObject*>*>(GOBJECTS_VA);\n")
        w(f"inline TArray<FNameEntry*>* GNames =\n"
          f"    reinterpret_cast<TArray<FNameEntry*>*>(GNAMES_VA);\n\n")

        w("inline const char* GetName(const UObject* Obj) {\n")
        w("    if (!Obj) return \"None\";\n")
        w("    DWORD idx = Obj->Name.Index;\n")
        w("    if (idx >= GNames->Count) return \"INVALID\";\n")
        w("    const FNameEntry* e = GNames->Data[idx];\n")
        w("    return e ? e->Name : \"NULL_ENTRY\";\n}\n\n")

        w("inline void ObjectDump(const wchar_t* path) {\n")
        w("    FILE* f = nullptr; _wfopen_s(&f, path, L\"w+\");\n")
        w("    if (!f) return;\n")
        w("    for (DWORD i = 0; i < GObjObjects->Count; ++i) {\n")
        w("        UObject* o = GObjObjects->Data[i];\n")
        w("        if (!o) continue;\n")
        w("        fprintf(f, \"Object[%06u] 0x%p  %s\\n\", i, o, GetName(o));\n")
        w("    }\n    fclose(f);\n}\n\n")

        w("inline void NameDump(const wchar_t* path) {\n")
        w("    FILE* f = nullptr; _wfopen_s(&f, path, L\"w+\");\n")
        w("    if (!f) return;\n")
        w("    for (DWORD i = 0; i < GNames->Count; ++i) {\n")
        w("        const FNameEntry* e = GNames->Data[i];\n")
        w("        if (!e) continue;\n")
        w("        fprintf(f, \"Name[%06u] %s\\n\", i, e->Name);\n")
        w("    }\n    fclose(f);\n}\n\n")

    # ── DMA section ─────────────────────────────────────────────────────────
    if target in ("dma", "both"):
        w("// ==================================================================\n")
        w("// DMA SDK  —  remote read via PCILeech / MemProcFS / LeechCore\n")
        w("//\n")
        w("// Requires: LeechCore.dll + MemProcFS.dll\n")
        w("// Headers:  leechcore.h  vmmdll.h  (PCILeech SDK)\n")
        w("// Libs:     leechcore.lib  vmmdll.lib\n")
        w("// ==================================================================\n\n")
        w("#ifdef UE3SDK_DMA\n\n")
        w("#include \"leechcore.h\"\n#include \"vmmdll.h\"\n\n")

        w("inline bool DMA_Read(VMM_HANDLE hVMM, DWORD pid,\n")
        w("                     ULONG64 va, void* out, SIZE_T size) {\n")
        w("    return VMMDLL_MemRead(hVMM, pid, va, (PBYTE)out, (DWORD)size);\n}\n\n")

        if is64:
            w("inline DWORD64 DMA_RPtr(VMM_HANDLE h, DWORD pid, ULONG64 va) {\n")
            w("    DWORD64 v = 0; DMA_Read(h, pid, va, &v, 8); return v;\n}\n\n")
        else:
            w("inline DWORD DMA_RPtr(VMM_HANDLE h, DWORD pid, ULONG64 va) {\n")
            w("    DWORD v = 0; DMA_Read(h, pid, va, &v, 4); return v;\n}\n\n")

        w("inline DWORD DMA_RDword(VMM_HANDLE h, DWORD pid, ULONG64 va) {\n")
        w("    DWORD v = 0; DMA_Read(h, pid, va, &v, 4); return v;\n}\n\n")

        w("struct DMA_TArray { ULONG64 Data; DWORD Count; DWORD Max; };\n")
        w("inline DMA_TArray DMA_ReadTArray(VMM_HANDLE h, DWORD pid, ULONG64 va) {\n")
        w("    DMA_TArray a{};\n")
        w(f"    a.Data  = DMA_RPtr  (h, pid, va);\n")
        w(f"    a.Count = DMA_RDword(h, pid, va + {ptr_sz});\n")
        w(f"    a.Max   = DMA_RDword(h, pid, va + {ptr_sz + 4});\n")
        w("    return a;\n}\n\n")

        w("inline std::string DMA_GetName(VMM_HANDLE hVMM, DWORD pid, ULONG64 objVA) {\n")
        w("    if (!objVA) return \"None\";\n")
        w(f"    DWORD nameIdx = DMA_RDword(hVMM, pid, objVA + NAME_FIELD_OFF);\n")
        w("    auto gn = DMA_ReadTArray(hVMM, pid, GNAMES_VA);\n")
        w("    if (!gn.Data || nameIdx >= gn.Count) return \"INVALID\";\n")
        w(f"    ULONG64 entryVA = DMA_RPtr(hVMM, pid, gn.Data + (ULONG64)nameIdx * {ptr_sz});\n")
        w("    if (!entryVA) return \"NULL_ENTRY\";\n")
        w("    char buf[512] = {};\n")
        w(f"    DMA_Read(hVMM, pid, entryVA + NAME_STR_OFF, buf, sizeof(buf) - 1);\n")
        w("    return buf;\n}\n\n")

        w("inline DWORD DMA_FindProcess(VMM_HANDLE hVMM, const char* name) {\n")
        w("    PVMMDLL_PROCESS_INFORMATION pInfo = nullptr; SIZE_T n = 0;\n")
        w("    if (!VMMDLL_ProcessGetInformationAll(hVMM, &pInfo, &n)) return 0;\n")
        w("    DWORD pid = 0;\n")
        w("    for (SIZE_T i = 0; i < n && !pid; ++i)\n")
        w("        if (_stricmp(pInfo[i].szNameLong, name) == 0) pid = pInfo[i].dwPID;\n")
        w("    VMMDLL_MemFree(pInfo); return pid;\n}\n\n")

        w("inline void DMA_NameDump(VMM_HANDLE hVMM, DWORD pid, const wchar_t* path) {\n")
        w("    FILE* f = nullptr; _wfopen_s(&f, path, L\"w+\");\n")
        w("    if (!f) return;\n")
        w("    auto gn = DMA_ReadTArray(hVMM, pid, GNAMES_VA);\n")
        w("    for (DWORD i = 0; i < gn.Count; ++i) {\n")
        w(f"        ULONG64 eVA = DMA_RPtr(hVMM, pid, gn.Data + (ULONG64)i * {ptr_sz});\n")
        w("        if (!eVA) continue;\n")
        w("        char buf[512] = {};\n")
        w(f"        DMA_Read(hVMM, pid, eVA + NAME_STR_OFF, buf, sizeof(buf) - 1);\n")
        w("        fprintf(f, \"Name[%06u] %s\\n\", i, buf);\n")
        w("    }\n    fclose(f);\n}\n\n")

        w("inline void DMA_ObjectDump(VMM_HANDLE hVMM, DWORD pid, const wchar_t* path) {\n")
        w("    FILE* f = nullptr; _wfopen_s(&f, path, L\"w+\");\n")
        w("    if (!f) return;\n")
        w("    auto go = DMA_ReadTArray(hVMM, pid, GOBJECTS_VA);\n")
        w("    for (DWORD i = 0; i < go.Count; ++i) {\n")
        w(f"        ULONG64 oVA = DMA_RPtr(hVMM, pid, go.Data + (ULONG64)i * {ptr_sz});\n")
        w("        if (!oVA) continue;\n")
        w("        auto name = DMA_GetName(hVMM, pid, oVA);\n")
        w("        fprintf(f, \"Object[%06u] 0x%llX  %s\\n\",\n")
        w("                i, (unsigned long long)oVA, name.c_str());\n")
        w("    }\n    fclose(f);\n}\n\n")

        w("#endif // UE3SDK_DMA\n")

    return buf.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
# Python generation
# ─────────────────────────────────────────────────────────────────────────────

def _gen_python(names: Dict[int, str], objects: List[Dict], cfg: dict) -> str:
    gobj_va  = cfg["gobj_va"]
    gnam_va  = cfg["gnam_va"]
    noff     = cfg["name_off"]
    nstroff  = cfg["namestr_off"]
    is64     = cfg["is64"]
    target   = cfg["sdk_target"]
    src_desc = cfg.get("source_desc", "offline")

    ptr_sz   = 8 if is64 else 4
    ptr_fmt  = "Q" if is64 else "I"
    class_names = _collect_classes(objects)

    buf = io.StringIO()
    w   = buf.write

    w("# ==================================================================\n")
    w("# Unreal Engine 3 — Auto-generated Python SDK skeleton\n")
    w(f"# Generated by UESDKGen  |  source: {src_desc}\n")
    w(f"# GObjects: {gobj_va}  GNames: {gnam_va}\n")
    w(f"# Names: {len(names):,}   Objects: {len(objects):,}\n")
    w("# ==================================================================\n\n")

    w("from __future__ import annotations\n")
    w("import ctypes, ctypes.wintypes as _wt, struct\n")
    w("from typing import Optional\n\n")

    w("# ── Constants ─────────────────────────────────────────────────────\n")
    w(f"GOBJECTS_VA    = {gobj_va}\n")
    w(f"GNAMES_VA      = {gnam_va}\n")
    w(f"NAME_FIELD_OFF = {noff}\n")
    w(f"NAME_STR_OFF   = {nstroff}\n")
    w(f"PTR_SZ         = {ptr_sz}\n")
    w(f"PTR_FMT        = '{ptr_fmt}'\n\n")

    # ── Native section ──────────────────────────────────────────────────────
    if target in ("native", "both"):
        w("# ==================================================================\n")
        w("# NATIVE — ReadProcessMemory\n")
        w("# ==================================================================\n\n")

        w("_k32 = ctypes.WinDLL('kernel32', use_last_error=True)\n\n")

        w("def open_process(pid: int) -> int:\n")
        w("    h = _k32.OpenProcess(0x0010 | 0x0400, False, pid)\n")
        w("    if not h: raise OSError(f'OpenProcess({pid}) failed. Run as Admin.')\n")
        w("    return h\n\n")

        w("def rpm(h: int, va: int, size: int) -> Optional[bytes]:\n")
        w("    buf = (ctypes.c_byte * size)()\n")
        w("    read = ctypes.c_size_t(0)\n")
        w("    ok = _k32.ReadProcessMemory(h, ctypes.c_void_p(va), buf, size, ctypes.byref(read))\n")
        w("    return bytes(buf[:read.value]) if ok else None\n\n")

        w("def rptr(h: int, va: int) -> int:\n")
        w(f"    d = rpm(h, va, {ptr_sz})\n")
        w(f"    return struct.unpack_from('<{ptr_fmt}', d)[0] if d else 0\n\n")

        w("def ru32(h: int, va: int) -> int:\n")
        w("    d = rpm(h, va, 4)\n")
        w("    return struct.unpack_from('<I', d)[0] if d else 0\n\n")

        w("def read_str(h: int, va: int, max_b: int = 512) -> str:\n")
        w("    d = rpm(h, va, max_b)\n")
        w("    if not d: return ''\n")
        w("    end = d.find(b'\\x00')\n")
        w("    return (d[:end] if end >= 0 else d).decode('ascii', errors='replace')\n\n")

        w("def get_name(h: int, obj_va: int) -> str:\n")
        w(f"    idx = ru32(h, obj_va + NAME_FIELD_OFF)\n")
        w("    gn_data = rptr(h, GNAMES_VA)\n")
        w("    gn_count = ru32(h, GNAMES_VA + PTR_SZ)\n")
        w("    if not gn_data or idx >= gn_count: return 'INVALID'\n")
        w(f"    entry_va = rptr(h, gn_data + idx * PTR_SZ)\n")
        w("    if not entry_va: return 'NULL_ENTRY'\n")
        w("    return read_str(h, entry_va + NAME_STR_OFF)\n\n")

        w("def dump_names(h: int) -> dict:\n")
        w("    gn_data  = rptr(h, GNAMES_VA)\n")
        w("    gn_count = ru32(h, GNAMES_VA + PTR_SZ)\n")
        w("    out = {}\n")
        w("    for i in range(gn_count):\n")
        w(f"        e = rptr(h, gn_data + i * PTR_SZ)\n")
        w("        if e: out[i] = read_str(h, e + NAME_STR_OFF)\n")
        w("    return out\n\n")

        w("def dump_objects(h: int, names: dict) -> list:\n")
        w("    go_data  = rptr(h, GOBJECTS_VA)\n")
        w("    go_count = ru32(h, GOBJECTS_VA + PTR_SZ)\n")
        w("    out = []\n")
        w("    for i in range(go_count):\n")
        w(f"        ptr = rptr(h, go_data + i * PTR_SZ)\n")
        w("        if not ptr: continue\n")
        w("        ni = ru32(h, ptr + NAME_FIELD_OFF)\n")
        w("        out.append({'index': i, 'ptr': ptr, 'ni': ni,\n")
        w("                    'name': names.get(ni, f'?{ni}')})\n")
        w("    return out\n\n")

        if class_names:
            w("# ── UObject ctypes wrappers (pack=4 for 32-bit) ─────────────────\n")
            w("class UObject(ctypes.LittleEndianStructure):\n")
            w("    _pack_ = 4\n")
            w(f"    _fields_ = [('_pad', ctypes.c_byte * {noff}),\n")
            w("                ('name_index', ctypes.c_uint32),\n")
            w("                ('name_number', ctypes.c_uint32)]\n\n")
            for cn in class_names[:40]:
                w(f"class {cn}(UObject): pass\n")
            w("\n")

    # ── DMA section ─────────────────────────────────────────────────────────
    if target in ("dma", "both"):
        w("# ==================================================================\n")
        w("# DMA — vmmpy / PCILeech MemProcFS\n")
        w("# pip install vmmpy\n")
        w("# ==================================================================\n\n")

        w("try:\n    import vmmpy as _vmmpy\n    HAS_VMMPY = True\n")
        w("except ImportError:\n    _vmmpy = None; HAS_VMMPY = False\n\n")

        w("class DmaReader:\n")
        w("    def __init__(self, device: str, process_name: str) -> None:\n")
        w("        if not HAS_VMMPY: raise ImportError('pip install vmmpy')\n")
        w("        self._vmm  = _vmmpy.Vmm(['-device', device])\n")
        w("        procs = self._vmm.process_list()\n")
        w("        tgt   = next((p for p in procs\n")
        w("                      if p.get('name','').lower() == process_name.lower()), None)\n")
        w("        if not tgt: raise RuntimeError(f'Process {process_name!r} not found.')\n")
        w("        self._proc = self._vmm.process(tgt['pid'])\n\n")

        w("    def read(self, va: int, size: int) -> Optional[bytes]:\n")
        w("        try: return bytes(self._proc.memory.read(va, size))\n")
        w("        except Exception: return None\n\n")

        w("    def rptr(self, va: int) -> int:\n")
        w(f"        d = self.read(va, {ptr_sz})\n")
        w(f"        return struct.unpack_from('<{ptr_fmt}', d)[0] if d else 0\n\n")

        w("    def ru32(self, va: int) -> int:\n")
        w("        d = self.read(va, 4)\n")
        w("        return struct.unpack_from('<I', d)[0] if d else 0\n\n")

        w("    def read_str(self, va: int, max_b: int = 512) -> str:\n")
        w("        d = self.read(va, max_b)\n")
        w("        if not d: return ''\n")
        w("        end = d.find(b'\\x00')\n")
        w("        return (d[:end] if end >= 0 else d).decode('ascii', errors='replace')\n\n")

        w("    def get_name(self, obj_va: int) -> str:\n")
        w(f"        idx = self.ru32(obj_va + NAME_FIELD_OFF)\n")
        w("        gn_data  = self.rptr(GNAMES_VA)\n")
        w("        gn_count = self.ru32(GNAMES_VA + PTR_SZ)\n")
        w("        if not gn_data or idx >= gn_count: return 'INVALID'\n")
        w(f"        entry_va = self.rptr(gn_data + idx * PTR_SZ)\n")
        w("        if not entry_va: return 'NULL_ENTRY'\n")
        w("        return self.read_str(entry_va + NAME_STR_OFF)\n\n")

        w("    def dump_names(self) -> dict:\n")
        w("        gn_data  = self.rptr(GNAMES_VA)\n")
        w("        gn_count = self.ru32(GNAMES_VA + PTR_SZ)\n")
        w("        out = {}\n")
        w("        for i in range(gn_count):\n")
        w(f"            e = self.rptr(gn_data + i * PTR_SZ)\n")
        w("            if e: out[i] = self.read_str(e + NAME_STR_OFF)\n")
        w("        return out\n\n")

        w("    def dump_objects(self, names: dict) -> list:\n")
        w("        go_data  = self.rptr(GOBJECTS_VA)\n")
        w("        go_count = self.ru32(GOBJECTS_VA + PTR_SZ)\n")
        w("        out = []\n")
        w("        for i in range(go_count):\n")
        w(f"            ptr = self.rptr(go_data + i * PTR_SZ)\n")
        w("            if not ptr: continue\n")
        w("            ni = self.ru32(ptr + NAME_FIELD_OFF)\n")
        w("            out.append({'index': i, 'ptr': ptr, 'ni': ni,\n")
        w("                        'name': names.get(ni, f'?{ni}')})\n")
        w("        return out\n")

    return buf.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
# Public entry-point
# ─────────────────────────────────────────────────────────────────────────────

def generate_sdk(names: Dict[int, str], objects: List[Dict], cfg: dict) -> str:
    """Generate SDK text.  cfg['sdk_lang'] selects 'cpp' or 'python'."""
    lang = cfg.get("sdk_lang", "cpp")
    if lang == "python":
        return _gen_python(names, objects, cfg)
    return _gen_cpp(names, objects, cfg)
