"""
Port of src/utils/managedEnvConstants.ts
"""
from __future__ import annotations

from typing import FrozenSet, Tuple


PROVIDER_MANAGED_ENV_VARS: FrozenSet[str] = frozenset(
    [
        "vivian_CODE_PROVIDER_MANAGED_BY_HOST",
        "vivian_CODE_USE_BEDROCK",
        "vivian_CODE_USE_VERTEX",
        "vivian_CODE_USE_FOUNDRY",
        "ANTHROPIC_BASE_URL",
        "ANTHROPIC_BEDROCK_BASE_URL",
        "ANTHROPIC_VERTEX_BASE_URL",
        "ANTHROPIC_FOUNDRY_BASE_URL",
        "ANTHROPIC_FOUNDRY_RESOURCE",
        "ANTHROPIC_VERTEX_PROJECT_ID",
        "CLOUD_ML_REGION",
        "ANTHROPIC_API_KEY",
        "ANTHROPIC_AUTH_TOKEN",
        "vivian_CODE_OAUTH_TOKEN",
        "AWS_BEARER_TOKEN_BEDROCK",
        "ANTHROPIC_FOUNDRY_API_KEY",
        "vivian_CODE_SKIP_BEDROCK_AUTH",
        "vivian_CODE_SKIP_VERTEX_AUTH",
        "vivian_CODE_SKIP_FOUNDRY_AUTH",
        "ANTHROPIC_MODEL",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES",
        "ANTHROPIC_DEFAULT_OPUS_MODEL",
        "ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION",
        "ANTHROPIC_DEFAULT_OPUS_MODEL_NAME",
        "ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES",
        "ANTHROPIC_DEFAULT_SONNET_MODEL",
        "ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION",
        "ANTHROPIC_DEFAULT_SONNET_MODEL_NAME",
        "ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES",
        "ANTHROPIC_SMALL_FAST_MODEL",
        "ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION",
        "vivian_CODE_SUBAGENT_MODEL",
    ]
)

PROVIDER_MANAGED_ENV_PREFIXES: Tuple[str, ...] = (
    "VERTEX_REGION_vivian_",
)


# Dangerous shell settings that can execute arbitrary shell code
DANGEROUS_SHELL_SETTINGS: Tuple[str, ...] = (
    "apiKeyHelper",
    "awsAuthRefresh",
    "awsCredentialExport",
    "gcpAuthRefresh",
    "otelHeadersHelper",
    "statusLine",
)
# Safe environment variables that can be applied before trust dialog.
SAFE_ENV_VARS: FrozenSet[str] = frozenset(
    [
        "ANTHROPIC_CUSTOM_HEADERS",
        "ANTHROPIC_CUSTOM_MODEL_OPTION",
        "ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION",
        "ANTHROPIC_CUSTOM_MODEL_OPTION_NAME",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES",
        "ANTHROPIC_DEFAULT_OPUS_MODEL",
        "ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION",
        "ANTHROPIC_DEFAULT_OPUS_MODEL_NAME",
        "ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES",
        "ANTHROPIC_DEFAULT_SONNET_MODEL",
        "ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION",
        "ANTHROPIC_DEFAULT_SONNET_MODEL_NAME",
        "ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES",
        "ANTHROPIC_FOUNDRY_API_KEY",
        "ANTHROPIC_MODEL",
        "ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION",
        "ANTHROPIC_SMALL_FAST_MODEL",
        "AWS_DEFAULT_REGION",
        "AWS_PROFILE",
        "AWS_REGION",
        "BASH_DEFAULT_TIMEOUT_MS",
        "BASH_MAX_OUTPUT_LENGTH",
        "BASH_MAX_TIMEOUT_MS",
        "vivian_BASH_MAINTAIN_PROJECT_WORKING_DIR",
        "vivian_CODE_API_KEY_HELPER_TTL_MS",
        "vivian_CODE_DISABLE_EXPERIMENTAL_BETAS",
        "vivian_CODE_DISABLE_NONESSENTIAL_TRAFFIC",
        "vivian_CODE_DISABLE_TERMINAL_TITLE",
        "vivian_CODE_ENABLE_TELEMETRY",
        "vivian_CODE_EXPERIMENTAL_AGENT_TEAMS",
        "vivian_CODE_IDE_SKIP_AUTO_INSTALL",
        "vivian_CODE_MAX_OUTPUT_TOKENS",
        "vivian_CODE_SKIP_BEDROCK_AUTH",
        "vivian_CODE_SKIP_FOUNDRY_AUTH",
        "vivian_CODE_SKIP_VERTEX_AUTH",
        "vivian_CODE_SUBAGENT_MODEL",
        "vivian_CODE_USE_BEDROCK",
        "vivian_CODE_USE_FOUNDRY",
        "vivian_CODE_USE_VERTEX",
        "DISABLE_AUTOUPDATER",
        "DISABLE_BUG_COMMAND",
        "DISABLE_COST_WARNINGS",
        "DISABLE_ERROR_REPORTING",
        "DISABLE_FEEDBACK_COMMAND",
        "DISABLE_TELEMETRY",
        "ENABLE_TOOL_SEARCH",
        "MAX_MCP_OUTPUT_TOKENS",
        "MAX_THINKING_TOKENS",
        "MCP_TIMEOUT",
        "MCP_TOOL_TIMEOUT",
        "OTEL_EXPORTER_OTLP_HEADERS",
        "OTEL_EXPORTER_OTLP_LOGS_HEADERS",
        "OTEL_EXPORTER_OTLP_LOGS_PROTOCOL",
        "OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE",
        "OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY",
        "OTEL_EXPORTER_OTLP_METRICS_HEADERS",
        "OTEL_EXPORTER_OTLP_METRICS_PROTOCOL",
        "OTEL_EXPORTER_OTLP_PROTOCOL",
        "OTEL_EXPORTER_OTLP_TRACES_HEADERS",
        "OTEL_LOG_TOOL_DETAILS",
        "OTEL_LOG_USER_PROMPTS",
        "OTEL_LOGS_EXPORT_INTERVAL",
        "OTEL_LOGS_EXPORTER",
        "OTEL_METRIC_EXPORT_INTERVAL",
        "OTEL_METRICS_EXPORTER",
        "OTEL_METRICS_INCLUDE_ACCOUNT_UUID",
        "OTEL_METRICS_INCLUDE_SESSION_ID",
        "OTEL_METRICS_INCLUDE_VERSION",
        "OTEL_RESOURCE_ATTRIBUTES",
        "USE_BUILTIN_RIPGREP",
        "VERTEX_REGION_vivian_3_5_HAIKU",
        "VERTEX_REGION_vivian_3_5_SONNET",
        "VERTEX_REGION_vivian_3_7_SONNET",
        "VERTEX_REGION_vivian_4_0_OPUS",
        "VERTEX_REGION_vivian_4_0_SONNET",
        "VERTEX_REGION_vivian_4_1_OPUS",
        "VERTEX_REGION_vivian_4_5_SONNET",
        "VERTEX_REGION_vivian_4_6_SONNET",
        "VERTEX_REGION_vivian_HAIKU_4_5",
    ]
)


def isProviderManagedEnvVar(key: str) -> bool:
    upper = key.upper()
    return upper in PROVIDER_MANAGED_ENV_VARS or any(
        upper.startswith(prefix) for prefix in PROVIDER_MANAGED_ENV_PREFIXES
    )


is_provider_managed_env_var = isProviderManagedEnvVar

